<?php
	echo script_tag(plugin_url("fastclick/fastclick.js"));
	echo script_tag(plugin_url("nprogress/nprogress.min.js"));
	echo script_tag(plugin_url("select2/js/select2.full.min.js"));
	echo script_tag(js_url("app.js"));
	echo script_tag(js_url("js.cookie.js"));
	echo script_tag(plugin_url("toastr-master/toastr.js"));
	echo script_tag(plugin_url("loaders/blockui.min.js"));
	echo script_tag(plugin_url("bootstrap-progressbar/bootstrap-progressbar.min.js"));
	echo script_tag(plugin_url("datatables-1.10.15/js/jquery.dataTables.js"));
	echo script_tag(plugin_url("datatables-1.10.15/js/dataTables.bootstrap.js"));
	echo script_tag(plugin_url("bootstrap-colorpicker/js/bootstrap-colorpicker.js"));
	echo script_tag(plugin_url("datetimepicker/jquery.datetimepicker.js"));
	echo script_tag(plugin_url("jquery.autocomplete/jquery.autocomplete.js"));
	echo script_tag(plugin_url("nestable/jquery.nestable.js"));
	echo script_tag(plugin_url("media/jquery.media.js"));
	echo script_tag(plugin_url("tags/tokenfield.min.js"));
	echo script_tag(plugin_url("nestable/jquery.nestable.js"));
	echo script_tag(plugin_url("html2canvas/html2canvas.min.js"));
	echo script_tag(plugin_url("html2canvas/html2canvas.svg.min.js"));
	echo script_tag(plugin_url("fullcalendar/dist/moment.min.js"));
	echo script_tag(js_url("lazysizes.min.js"));
	// echo script_tag(js_url("Chart.PieceLabel.min.js"));
	echo script_tag(plugin_url("fullcalendar/dist/fullcalendar.min.js"));
	echo script_tag(plugin_url("amcharts/amcharts/amcharts.js"));
	echo script_tag(plugin_url("amcharts/amcharts/serial.js"));
	echo script_tag(plugin_url("amcharts/amcharts/plugins/export/export.min.js"));
	echo script_tag(plugin_url("amcharts/amcharts/themes/export/light.js"));
	echo script_tag(js_url("custom.js"));
	echo script_tag(js_url("main.js"));
?> 